# .github/workflows/keep-alive.yml

name: Multi-URL Keep-Alive

on:
  schedule:
    - cron: '*/30 * * * *'  
  workflow_dispatch:

jobs:
  ping-urls:
    runs-on: ubuntu-latest
    strategy:
      # 定义一个名为 url 的矩阵变量
      matrix:
        url:
          - 'https://starsdream666-space-manager.hf.space'
          - 'https://starsdream666-mynote.hf.space/'
          # 在这里添加更多你想要监控的URL

    steps:
      - name: Ping ${{ matrix.url }}
        # 在步骤名称和运行命令中，使用 ${{ matrix.url }} 来引用当前正在处理的URL
        run: curl --fail "${{ matrix.url }}"
